openapi: 3.0.3
info:
  title: CICS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
paths:
  /v1/image/get:
    post:
      summary: Generate CBOM from existing image
      requestBody:
        required: true
        content:
          application/json:    
            schema:
              type: object
              properties:
                image:
                  description: Identifier for Image
                  example: "nginx"
                  type: string
                plugins:
                  type: array
                  example: 
                    - "javasecurity"
                    - "secrets"
                    - "certificates"
                  description: Plugins to activate
                  items:
                    type: string
                    description: Name of a plugin
                bom:
                  description: CBOM to verify/expand
                  $ref: "https://raw.githubusercontent.com/CycloneDX/specification/master/schema/bom-1.6.schema.json"
              required: 
                - image
      responses:
        '200':
          description: OK
          content:
            application/vnd.cyclonedx+json:
              schema:
                $ref: "https://raw.githubusercontent.com/CycloneDX/specification/master/schema/bom-1.6.schema.json"
        default:
          description: Unexpected error
          content:
            application/json: 
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
schemas:
    BOM:
      $ref: "https://raw.githubusercontent.com/CycloneDX/specification/master/schema/bom-1.6.schema.json"